# Name to identify the schedule, must be unique across all schedules.
string name

# A cron string describing the schedule.
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
string schedule

# unix time in secs
int64 start_at

# unix time in secs
int64 finish_at 9223372036854775807

Payload payload
