# Registers a new recurring schedule. Existing schedule with the same name will be replaced.

# The following fields are ignored:
#   - created_at
Schedule schedule

---

# Confirmation that the schedule is successfully registered
bool success

# If success is false, this provides a reason for the failure.
string message
