# Query list of submitted tasks | Get service call

# Input the generated task ID during submission
# if empty, provide all Submitted Tasks
string[] task_ids

---

bool success

DispatchStates states
