# Revive a previously cancelled or failed task. This will reinitiate
# a bidding sequence to reassign this task.

# Identifier for who is requesting the service
string requester

# task that was previously cancelled or failed
string task_id

---

# Confirmation that this service call is processed
bool success

