# Query ID to request a full participants list for
uint64 query_id

# Version to request changes from; ignored if full_update is true
uint64 version

# Request a full update rather than from a specific version
bool full_update false

---

# Response to the request
ScheduleIdentity node_id
uint8 REQUEST_ACCEPTED=1
uint8 UNKNOWN_QUERY_ID=2
uint8 ERROR=3
uint8 result
string error
